<?php

namespace Database\Seeders;

use App\Models\SEO;
use Illuminate\Database\Seeder;

class SEOSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'page_slug' => 'home',
                'page_title' => 'Home',
                'meta_title' => 'Snap Spirit Studio - Premium Wedding & Commercial Photography in Ahmedabad',
                'meta_description' => 'Award-winning photography & cinematography studio in Ahmedabad. Professional wedding, event, and commercial photography services. Founded by Chintan Mali. Expert visual storytelling for brands and businesses.',
                'meta_keywords' => 'photography Ahmedabad, cinematography Ahmedabad, wedding photographer Ahmedabad, professional photography, event photography, corporate photography, video production Ahmedabad',
                'og_title' => 'Snap Spirit Studio - Premium Photography & Cinematography in Ahmedabad',
                'og_description' => 'Award-winning visual storytelling for weddings, events, brands, and creative projects. Professional photography and cinematography studio in Ahmedabad.',
                'og_image' => asset('assets/images/og-home.jpg'),
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio, Ahmedabad',
                'twitter_card' => 'summary_large_image',
                'twitter_title' => 'Snap Spirit Studio - Ahmedabad',
                'twitter_description' => 'Premium Photography & Cinematography in Ahmedabad',
                'page_type' => 'homepage',
                'is_active' => true,
            ],
            [
                'page_slug' => 'about',
                'page_title' => 'About Us',
                'meta_title' => 'About Snap Spirit Studio - Photography & Cinematography Ahmedabad',
                'meta_description' => 'Discover Snap Spirit Studio - A premium photography and cinematography studio in Ahmedabad founded by Chintan Mali. Specializing in weddings, events, and commercial photography with artistic excellence and technical mastery.',
                'meta_keywords' => 'Snap Spirit Studio Ahmedabad, Chintan Mali cinematographer, photography studio Ahmedabad, best photographer Ahmedabad, professional photography services',
                'og_title' => 'About Snap Spirit Studio - Ahmedabad\'s Premier Photography Studio',
                'og_description' => 'Learn about our journey, passion, and commitment to visual storytelling excellence in Ahmedabad.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio, Ahmedabad',
                'twitter_card' => 'summary',
                'page_type' => 'about',
                'is_active' => true,
            ],
            [
                'page_slug' => 'services',
                'page_title' => 'Services',
                'meta_title' => 'Professional Photography & Videography Services in Ahmedabad - Snap Spirit Studio',
                'meta_description' => 'Comprehensive photography and videography services in Ahmedabad. Wedding photography, event coverage, corporate photography, brand shoots, and professional cinematography.',
                'meta_keywords' => 'photography services Ahmedabad, wedding photography, event photography, corporate photography, commercial photography Ahmedabad, videography services',
                'og_title' => 'Our Services - Snap Spirit Studio Ahmedabad',
                'og_description' => 'Premium photography and videography services for weddings, events, corporate projects, and brand campaigns in Ahmedabad.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio, Ahmedabad',
                'twitter_card' => 'summary',
                'page_type' => 'services',
                'is_active' => true,
            ],
            [
                'page_slug' => 'portfolio',
                'page_title' => 'Portfolio',
                'meta_title' => 'Our Work - Portfolio | Snap Spirit Studio',
                'meta_description' => 'View our impressive portfolio of wedding photography, event coverage, and creative projects showcasing our expertise and style.',
                'meta_keywords' => 'portfolio, work samples, wedding photography, event photography, photography projects',
                'og_title' => 'Our Portfolio - Snap Spirit Studio',
                'og_description' => 'Explore our stunning collection of photography and cinematography projects.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary_large_image',
                'page_type' => 'portfolio',
                'is_active' => true,
            ],
            [
                'page_slug' => 'team',
                'page_title' => 'Our Team',
                'meta_title' => 'Meet Our Team - Snap Spirit Studio',
                'meta_description' => 'Meet the talented photographers and videographers behind Snap Spirit Studio. Dedicated professionals with years of experience.',
                'meta_keywords' => 'team, photographers, videographers, professionals, creative team',
                'og_title' => 'Our Team - Snap Spirit Studio',
                'og_description' => 'Talented photographers and videographers dedicated to capturing your stories.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary',
                'page_type' => 'team',
                'is_active' => true,
            ],
            [
                'page_slug' => 'gallery',
                'page_title' => 'Gallery',
                'meta_title' => 'Photo Gallery - Snap Spirit Studio',
                'meta_description' => 'Browse our beautiful gallery of wedding, event, and commercial photography. High-quality images showcasing our work.',
                'meta_keywords' => 'gallery, photos, images, wedding gallery, event gallery',
                'og_title' => 'Photo Gallery - Snap Spirit Studio',
                'og_description' => 'Stunning collection of our photography work.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary_large_image',
                'page_type' => 'gallery',
                'is_active' => true,
            ],
            [
                'page_slug' => 'contact',
                'page_title' => 'Contact Us',
                'meta_title' => 'Contact Snap Spirit Studio - Get in Touch',
                'meta_description' => 'Get in touch with Snap Spirit Studio. Share your project details and let us help capture your special moments.',
                'meta_keywords' => 'contact, inquiry, photography booking, get in touch',
                'og_title' => 'Contact Snap Spirit Studio',
                'og_description' => 'Reach out to us for your photography and videography needs.',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary',
                'page_type' => 'contact',
                'is_active' => true,
            ],
            [
                'page_slug' => 'privacy-policy',
                'page_title' => 'Privacy Policy',
                'meta_title' => 'Privacy Policy - Snap Spirit Studio',
                'meta_description' => 'Read our privacy policy to understand how we protect and use your personal information.',
                'meta_keywords' => 'privacy, privacy policy, data protection',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary',
                'page_type' => 'legal',
                'is_active' => true,
            ],
            [
                'page_slug' => 'terms',
                'page_title' => 'Terms & Conditions',
                'meta_title' => 'Terms & Conditions - Snap Spirit Studio',
                'meta_description' => 'Review our terms and conditions for using Snap Spirit Studio services.',
                'meta_keywords' => 'terms, conditions, legal, terms of service',
                'og_type' => 'website',
                'robots' => 'index, follow',
                'author' => 'Snap Spirit Studio',
                'twitter_card' => 'summary',
                'page_type' => 'legal',
                'is_active' => true,
            ],
        ];

        foreach ($pages as $page) {
            SEO::updateOrCreate(
                ['page_slug' => $page['page_slug']],
                $page
            );
        }
    }
}
